package com.its.mobile.finball.ui.item

object CostsCategoryItem {
    const val KEY_COSTS_CATEGORY_FOOD = 1
    const val KEY_COSTS_CATEGORY_COMMUNAL_RENT = 2
    const val KEY_COSTS_CATEGORY_MOB_INTERNET_TV = 3
    const val KEY_COSTS_CATEGORY_CLOTHING_SHOES = 4
    const val KEY_COSTS_CATEGORY_TRANSPORT = 5
    const val KEY_COSTS_CATEGORY_FUN = 6
    const val KEY_COSTS_CATEGORY_REST = 7
    const val KEY_COSTS_CATEGORY_STUDY = 8
    const val KEY_COSTS_CATEGORY_CHILDREN = 9
    const val KEY_COSTS_CATEGORY_PARENTS = 10
    const val KEY_COSTS_CATEGORY_BELOVED = 11
    const val KEY_COSTS_CATEGORY_CARE_YOURSELF = 12
    const val KEY_COSTS_CATEGORY_CARE_HOME = 13
    const val KEY_COSTS_CATEGORY_HEALTH_SPORT = 14
    const val KEY_COSTS_CATEGORY_GIFT = 15
    const val KEY_COSTS_CATEGORY_PETS = 16
    const val KEY_COSTS_CATEGORY_HOBBY = 17
    const val KEY_COSTS_CATEGORY_CREDIT = 18
    const val KEY_COSTS_CATEGORY_INSURANCE = 19
    const val KEY_COSTS_CATEGORY_REPAIR_FURNITURE_MACHINERY = 20
    const val KEY_COSTS_CATEGORY_INVESTMENT = 21
    const val KEY_COSTS_CATEGORY_UNPREDICTABLE = 22
}