package com.its.mobile.finball.ui.item

object RevenueCategoryItem {
    const val KEY_REVENUE_CATEGORY_SALARY = 1
    const val KEY_REVENUE_CATEGORY_SPONSOR = 2
    const val KEY_REVENUE_CATEGORY_BRIBE = 3
    const val KEY_REVENUE_CATEGORY_GIFT = 4
    const val KEY_REVENUE_CATEGORY_DIVIDENDS = 5
    const val KEY_REVENUE_CATEGORY_INVESTMENT = 6
    const val KEY_REVENUE_CATEGORY_INVESTMENT_ONE = 7
    const val KEY_REVENUE_CATEGORY_INVESTMENT_TWO = 8
    const val KEY_REVENUE_CATEGORY_INVESTMENT_THREE = 9
    const val KEY_REVENUE_CATEGORY_INVESTMENT_FOUR = 10
    const val KEY_REVENUE_CATEGORY_INVESTMENT_FIVE = 11
    const val KEY_REVENUE_CATEGORY_BUSINESS = 12
    const val KEY_REVENUE_CATEGORY_BUSINESS_ONE = 13
    const val KEY_REVENUE_CATEGORY_BUSINESS_TWO = 14
    const val KEY_REVENUE_CATEGORY_BUSINESS_THREE = 15
    const val KEY_REVENUE_CATEGORY_BUSINESS_FOUR = 16
    const val KEY_REVENUE_CATEGORY_BUSINESS_FIVE = 17
    const val KEY_REVENUE_CATEGORY_REALTY = 18
    const val KEY_REVENUE_CATEGORY_REALTY_ONE = 19
    const val KEY_REVENUE_CATEGORY_REALTY_TWO = 20
    const val KEY_REVENUE_CATEGORY_REALTY_THREE = 21
    const val KEY_REVENUE_CATEGORY_REALTY_FOUR = 22
    const val KEY_REVENUE_CATEGORY_REALTY_FIVE = 23
    const val KEY_REVENUE_CATEGORY_INSURANCE = 24
    const val KEY_REVENUE_CATEGORY_SECURITIES_SHARES = 25
    const val KEY_REVENUE_CATEGORY_CREDIT_BUTS = 26
    const val KEY_REVENUE_CATEGORY_UNPREDICTABLE = 27
    const val KEY_REVENUE_CATEGORY_GOV_BENEFIT = 28
}