package com.its.mobile.finball.ui.item

object RevenueCategoryItem {
    const val KEY_REVENUE_CATEGORY_SALARY = 1
    const val KEY_REVENUE_CATEGORY_SPONSOR = 2
    const val KEY_REVENUE_CATEGORY_BRIBE = 3
    const val KEY_REVENUE_CATEGORY_GIFT = 4
    const val KEY_REVENUE_CATEGORY_DIVIDENDS = 5
    const val KEY_REVENUE_CATEGORY_INVESTMENT = 6
    const val KEY_REVENUE_CATEGORY_BUSINESS = 7
    const val KEY_REVENUE_CATEGORY_REALTY = 8
    const val KEY_REVENUE_CATEGORY_INSURANCE = 9
    const val KEY_REVENUE_CATEGORY_SECURITIES_SHARES = 10
    const val KEY_REVENUE_CATEGORY_CREDIT_BUTS = 11
    const val KEY_REVENUE_CATEGORY_UNPREDICTABLE = 12
    const val KEY_REVENUE_CATEGORY_GOV_BENEFIT = 13
}